### ISSUE TITLE
Crafting Recipe Suggestion

### ISSUE THREAD

**Issue by mdfiot** [copygirl/PocketBags_Forge#1]
<blockquote class="twitter-tweet" lang="en"><p>What should the crafting recipe for the pouch be?</p>&mdash; copygirl (@koppeh) <a href="https://twitter.com/koppeh/statuses/504723536200888320">August 27, 2014</a></blockquote>

<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

What about paper for the crafting recipe?

![craft_pouch](https://cloud.githubusercontent.com/assets/6662689/4067838/5408c254-2e32-11e4-9455-fd312b683dfc.png)

I don't have a twitter...

**Comment by copygirl** [comment]
Not a bad idea, but a paper bag would be pretty weak.
I've decided for wool, string and leather in the middle.
